module.exports = {
    TASK_CREATED: 'TASK_CREATED',
    TASK_UPDATED: 'TASK_UPDATED',
    TASK_ASSIGNEES_UPDATED: 'TASK_ASSIGNEES_UPDATED',
    TASK_MOVED: 'TASK_MOVED',
    TASK_COMMENTED: 'TASK_COMMENTED',
    TASK_COMMENT_UPDATED: 'TASK_COMMENT_UPDATED',
    TASK_COMMENT_DELETED: 'TASK_COMMENT_DELETED',
    TASK_CLONED: 'TASK_CLONED',
    TASK_ATTACHMENT_ADDED: 'TASK_ATTACHMENT_ADDED',
    TASK_ATTACHMENT_DELETED: 'TASK_ATTACHMENT_DELETED',
    TASK_SUBTASK_ADDED: 'TASK_SUBTASK_ADDED',
    TASK_SUBTASK_UPDATED: 'TASK_SUBTASK_UPDATED',
    TASK_SUBTASK_DELETED: 'TASK_SUBTASK_DELETED',
    TASK_TIME_LOG_ADDED: 'TASK_TIME_LOG_ADDED',

    PROJECT_CREATED: 'PROJECT_CREATED',
    PROJECT_UPDATED: 'PROJECT_UPDATED',
    PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
    PROJECT_MEMBER_ADDED: 'PROJECT_MEMBER_ADDED',
    PROJECT_MEMBER_INVITED: 'PROJECT_MEMBER_INVITED',
    PROJECT_MEMBER_INVITATION_ACCEPTED: 'PROJECT_MEMBER_INVITATION_ACCEPTED',
    PROJECT_MEMBER_INVITATION_DECLINED: 'PROJECT_MEMBER_INVITATION_DECLINED',
    PROJECT_MEMBER_ROLE_UPDATED: 'PROJECT_MEMBER_ROLE_UPDATED',
    PROJECT_MEMBER_REMOVED: 'PROJECT_MEMBER_REMOVED',
    PROJECT_CLONED: 'PROJECT_CLONED',
    PROJECT_DELETED: 'PROJECT_DELETED',

    TASK_FILTER_SAVED: 'TASK_FILTER_SAVED',
    TASK_FILTER_DELETED: 'TASK_FILTER_DELETED',

    SYSTEM_SETTINGS_UPDATED: 'SYSTEM_SETTINGS_UPDATED',

    VERIFICATION_EMAIL_SENT: 'VERIFICATION_EMAIL_SENT',
    VERIFICATION_EMAIL_REREQUESTED: 'VERIFICATION_EMAIL_REREQUESTED',

    NOTIFICATION_EMAIL_REQUESTED: 'NOTIFICATION_EMAIL_REQUESTED'
};
